# Change these first
owner: ESSS # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: RF-DAP (Demo)
    url: https://rfdap-demo.esss.co
  - name: RF-DAP (ESSS)
    url: https://rfdap.esss.co
  - name: RF-DAP (Shell)
    url: https://shell-rfdap.esss.co
  - name: RF-DAP (FASE Training)
    url: https://fase-training.esss.co
  - name: RF-DAP (Trial)
    url: https://rfdap-trial1.esss.co
  - name: STORMS
    url: https://storms.esss.co
  - name: Atlantis
    url: https://atlantis.esss.co

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://storage.googleapis.com/site.esss.co/2018/01/esss.png
  name: ESSS Dev Upptime
  introTitle: "ESSS Dev uptime monitor"
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
